### ISSUE TITLE
Bug in MYJ implementation

### ISSUE THREAD

**Issue by LarissaReames** [ufs-community/MPAS-Model#36]
Issue description:

Model crash when MYJ PBL scheme is used due to variables being used before allocation. The problem is caused by:

1.  The case block for "MJY" in subroutine allocate_pbl of the PBL driver is missing, so all MYJ-specific physics arrays are unallocated.
2. A few variables that are being mistakenly used under case("MYJ") in the subroutine pbl_to_MPAS of the PBL driver that should only be used for case ("MYNN"). 

These were probably just accidents from the merge of NSSL_develop. I was able to fix the problem by copying in the allocation block from the NSSL_develop branch and removing the later lines with the offending variables (dqke_p, qbuoy_p, qdiss_p, qshear_p, qwt_p, rqsblten_p, rniblten_p, qkeadv_p). 

Compilation details: 
Compiled on Jet using the "jet_ifort" make option.

**Comment by joeolson42** [comment]
makes me wonder what else got messed up in that merge... thanks for catching it.

**Comment by LarissaReames** [comment]
Closed as addressed by #40
